# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: azure-openai-dotnet
metadata:
  template: azure-openai-dotnet@0.0.1-beta

infra:
  provider: bicep
  path: infra
  module: main

services:
  backend:
    project: ./app/backend
    language: dotnet
    host: function
    hooks:
      prepackage:
        posix:
          shell: sh
          run: dotnet build backend.csproj --configuration Release
          interactive: true
          continueOnError: false

  frontend:
    language: js
    project: ./app/frontend
    dist: dist
    host: appservice
    hooks:
      prepackage:
        posix:
          shell: sh
          run: npm install; npm run build
          interactive: true
          continueOnError: false

      predeploy:
        posix:
          shell: sh
          run: ../../scripts/frontend_env.sh ${BACKEND_URI} ${BACKEND_KEY}
          interactive: true
          continueOnError: false

      postdeploy:
        shell: sh
        run: ../../scripts/app_config.sh

hooks:
  preprovision:
    posix:
      shell: sh
      run: cd app/prepdocs && dotnet build
      interactive: true
      continueOnError: false

  postprovision:
    posix:
      shell: sh
      run: ./scripts/prepdoc.sh
      interactive: true
      continueOnError: false

  postdeploy:
    posix:
      shell: sh
      run: ./scripts/enable_semantic_search.sh
      interactive: true
      continueOnError: false

pipeline:
  provider: github
